modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Fexcraft/ZMP"
[[mods]]
modId="fvtm"
version="1.0.0"
displayName="Zack's Model Projects"
displayURL="https://fexcraft.net/wiki/mod/fvtm" 
#credits="" #optional
authors="FEX___96"
displayTest="IGNORE_ALL_VERSION"

description='''A pack containing models made by zackyboy18'''
